NursingHome/NursingHome.UI/Controllers/SocialWorkersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NursingHome.BLL;
using NursingHome.UI.Models;
using NursingHome.UI.Services;

namespace NursingHome.UI.Controllers
{
    public class SocialWorkersController : Controller
    {
        private readonly SocialDocumentService _socialDocumentService;
        private readonly UserUiService _userUiService;
        private readonly FileUiService _fileUiService;

        public SocialWorkersController(UserUiService userUiService, FileUiService fileUiService, SocialDocumentService socialDocumentService)
        {
            _userUiService = userUiService;
            _fileUiService = fileUiService;
            _socialDocumentService = socialDocumentService;
        }

        [HttpGet]
        public async Task<IActionResult> Upload()
        {
            var activeResidents = await _userUiService.GetActiveResidents();

            var model = new UploadSocialDocumentViewModel
            {
                Residents = activeResidents
                    .Select(u => new SelectListItem
                    {
                        Value = u.Id,
                        Text = $"{u.FirstName} {u.MiddleName} {u.LastName}"
                    })
                    .ToList()
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var documents = await _socialDocumentService.GetAll();

            var documentModels = documents
            .Select(d => new SocialDocumentViewModel
            {
                Id = d.Id,
                ResidentName = $"{d.Resident.FirstName} {d.Resident.MiddleName} {d.Resident.LastName}",
                FileName = d.FileName,
                FilePath = d.FilePath,
                UploadedOn = d.UploadedOn,
                UploadedBy = d.UploadedBy,
                DocumentType = d.DocumentType
            }).ToList();

            return View(documentModels);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(UploadSocialDocumentViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var isSuccessfullyUploaded = await _fileUiService.UploadSocialDocument(User, model);

            if (!isSuccessfullyUploaded)
            {
                return View(model);
            }

            return RedirectToAction(nameof(List));
        }
    }
}

NursingHome/NursingHome.UI/Views/SocialWorkers/List.cshtml
@model List<SocialDocumentViewModel>

<div class="d-flex align-items-center mb-3">
    <h3 class="margin-right-20">Социални документи</h3>
    <input type="text" id="socialDocsSearch" class="form-control" placeholder="Търси по име..." style="width: 50% !important; height: fit-content; margin-right: 20px">
    <a class="btn btn-darkBlue d-flex align-items-center justify-content-center" style="height: fit-content" asp-controller="SocialWorkers" asp-action="Upload">Добавяне на документ</a>
</div>

@if (Model.Any())
{
    <table id="socialDocsTable" class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>Потребител</th>
                <th>Тип</th>
                <th>Файл</th>
                <th>Качен на</th>
                <th>Качен от</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var doc in Model)
            {
                <tr>
                    <td>@doc.ResidentName</td>
                    <td>@doc.DocumentType.GetDisplayName()</td>
                    <td>@doc.FileName</td>
                    <td>@doc.UploadedOn.ToLocalTime().ToString("dd.MM.yyyy HH:mm")</td>
                    <td>@string.Concat(doc.UploadedBy.FirstName, " ", doc.UploadedBy.LastName)</td>
                    <td>
                        <a href="@doc.FilePath" target="_blank" class="btn btn-darkBlue">Отвори файла</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Няма качени документи.</p>
}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        setupTableSearch("socialDocsSearch", "#socialDocsTable");
    });
</script>

NursingHome/NursingHome.UI/Views/SocialWorkers/Upload.cshtml
@model UploadSocialDocumentViewModel;

<div class="d-flex justify-content-between align-items-center mb-3">
    <h3>Качване на социален документ</h3>
    <a class="btn btn-darkBlue d-flex align-items-center justify-content-center" style="height: fit-content" asp-controller="SocialWorkers" asp-action="List">Прегледай качени документи</a>
</div>

<form asp-action="Upload" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label asp-for="ResidentId" class="form-label">Потребител</label>
        <select asp-for="ResidentId" class="form-select" asp-items="Model.Residents" id="userSelectDocuments">
        </select>
        <span asp-validation-for="ResidentId" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="DocumentType" class="form-label">Тип документ</label>
        <select asp-for="DocumentType" class="form-select">
            @foreach (SocialDocumentType value in Enum.GetValues(typeof(SocialDocumentType)))
            {
                <option value="@value">@value.GetDisplayName()</option>
            }
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="File" class="form-label">Файл</label>
        <input asp-for="File" type="file" class="form-control" required/>
    </div>

    <button type="submit" class="btn btn-darkBlue">Качи</button>
</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#userSelectDocuments').select2({
                placeholder: 'Търси по име...',
                width: '100%' 
            });
        });
    </script>
}